# Generated by Django 5.1.1 on 2024-10-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModeloMensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_modelo", models.CharField(max_length=255)),
                (
                    "tipo_mensagem",
                    models.IntegerField(
                        choices=[(1, "SMS"), (2, "WhatsApp"), (3, "E-mail")]
                    ),
                ),
                ("conteudo_mensagem", models.TextField()),
            ],
        ),
    ]
