# Generated by Django 5.1.1 on 2025-03-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Campanha Ativa"),
                            ("inativa", "Campanha Inativa"),
                        ],
                        default="ativa",
                        max_length=50,
                    ),
                ),
                ("responsavel", models.CharField(max_length=255)),
                ("titulo", models.CharField(max_length=255)),
                ("data_envio", models.DateField()),
                ("hora_envio", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="EtapaFluxo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "E-mail"), ("whatsapp", "WhatsApp")],
                        max_length=10,
                    ),
                ),
                ("delay_intervalo", models.PositiveIntegerField(default=0)),
                (
                    "intervalo_tipo",
                    models.CharField(
                        choices=[("minutos", "Minutos"), ("horas", "Horas")],
                        default="horas",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExecucaoFluxo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("finalizado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="FluxoAutomatizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MensagemWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                ("enviado", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("enviada", "Enviada"), ("recebida", "Recebida")],
                        max_length=10,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModeloMensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_modelo", models.CharField(max_length=255)),
                (
                    "tipo_mensagem",
                    models.IntegerField(
                        choices=[(1, "SMS"), (2, "WhatsApp"), (3, "E-mail")]
                    ),
                ),
                ("conteudo_mensagem", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
