# Generated by Django 5.1.1 on 2025-03-30 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
        ("gethos_home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="execucaofluxo",
            name="contato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gethos_home.contato"
            ),
        ),
        migrations.AddField(
            model_name="execucaofluxo",
            name="fluxo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastros.fluxoautomatizado",
            ),
        ),
        migrations.AddField(
            model_name="etapafluxo",
            name="fluxo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etapas",
                to="cadastros.fluxoautomatizado",
            ),
        ),
        migrations.AddField(
            model_name="mensagemwhatsapp",
            name="contato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensagens_whatsapp_cadastros",
                to="gethos_home.contato",
            ),
        ),
        migrations.AddField(
            model_name="etapafluxo",
            name="mensagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastros.modelomensagem",
            ),
        ),
        migrations.AddField(
            model_name="campanha",
            name="mensagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastros.modelomensagem",
            ),
        ),
    ]
