# Generated by Django 5.1.1 on 2024-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_modelomensagem_data_criacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ativa", "Ativa"), ("inativa", "Inativa")],
                        default="ativa",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
