# Generated by Django 5.1.1 on 2024-11-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_campanha"),
    ]

    operations = [
        migrations.AddField(
            model_name="campanha",
            name="mensagem",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastros.modelomensagem",
            ),
            preserve_default=False,
        ),
    ]
