# Generated by Django 5.1.1 on 2024-11-02 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_campanha_mensagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campanha",
            name="descricao",
        ),
        migrations.AddField(
            model_name="campanha",
            name="data_envio",
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanha",
            name="hora_envio",
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanha",
            name="responsavel",
            field=models.CharField(default="Administrador", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanha",
            name="titulo",
            field=models.CharField(default="modelo teste", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campanha",
            name="status",
            field=models.CharField(
                choices=[("ativa", "Campanha Ativa"), ("inativa", "Campanha Inativa")],
                default="ativa",
                max_length=50,
            ),
        ),
    ]
