[phases.setup]
aptPkgs = ["build-essential", "libpq-dev"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/daphne -b 0.0.0.0 -p ${PORT} gethosapp.asgi:application"