[phases.setup]
nixPkgs = ["python3", "gcc", "libstdcxx", "postgresql"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn gethosapp.wsgi --bind 0.0.0.0:${PORT}"
