# Generated by Django 5.1.1 on 2025-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIEvoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone_usuario_api", models.CharField(max_length=15, unique=True)),
                ("nome_conexao", models.CharField(max_length=100)),
                ("data_conexao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CadastroEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_empresa", models.CharField(max_length=255)),
                ("cnpj_empresa", models.CharField(max_length=18, unique=True)),
                ("rua_empresa", models.CharField(max_length=255)),
                ("cep_empresa", models.CharField(max_length=9)),
                ("telefone_empresa", models.CharField(max_length=15)),
                (
                    "bairro_empresa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cidade_empresa", models.CharField(max_length=100)),
                ("estado_empresa", models.CharField(max_length=2)),
                (
                    "email_contato_empresa",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("data_criacao_user_empresa", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailSMTPUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_usuario", models.EmailField(max_length=254, unique=True)),
                ("chave_api_secret_usuario", models.CharField(max_length=255)),
                ("remetente_email_usuario", models.EmailField(max_length=254)),
                (
                    "servidor_smtp_usuario",
                    models.CharField(default="smtp.gmail.com", max_length=100),
                ),
                ("porta_smtp_usuario", models.IntegerField(default=587)),
                ("usa_tls_usuario", models.BooleanField(default=True)),
                ("data_atualizacao_usuario", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
