# Generated by Django 5.1.1 on 2025-04-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIEvoGetInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance_name", models.CharField(max_length=100, unique=True)),
                ("state", models.CharField(default="open", max_length=50)),
                ("api_key", models.CharField(max_length=255)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("json_data", models.JSONField(default=dict)),
            ],
        ),
    ]
