# Generated by Django 5.1.1 on 2025-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0002_apievogetinstance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apievogetinstance",
            name="json_data",
        ),
        migrations.AddField(
            model_name="apievogetinstance",
            name="qr_code_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
