# Generated by Django 5.1.1 on 2025-03-25 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gethos_home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FluxoCaptacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A fazer", "A fazer"),
                            ("Em andamento", "Em andamento"),
                            ("Concluído", "Concluído"),
                        ],
                        default="A fazer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gethos_home.contato",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
