# Generated by Django 5.1.1 on 2025-03-30 18:15

import django.db.models.deletion
import processos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gethos_home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusKanban",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FluxoCaptacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gethos_home.contato",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        default=processos.models.get_default_status,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processos.statuskanban",
                    ),
                ),
            ],
        ),
    ]
