# Generated by Django 5.1.1 on 2024-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FluxoCaptacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A fazer", "A fazer"),
                            ("Em andamento", "Em andamento"),
                            ("Concluído", "Concluído"),
                        ],
                        default="A fazer",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
