# Generated by Django 5.1.1 on 2025-02-28 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0012_delete_contactfunnel_delete_funnelstage"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fluxocaptacao",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="fluxocaptacao",
            name="contato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gethos_home.contato",
            ),
        ),
        migrations.AddField(
            model_name="fluxocaptacao",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fluxocaptacao",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
