# Generated by Django 5.1.1 on 2025-03-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
