# Generated by Django 5.1.1 on 2024-10-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="empresa",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
