# Generated by Django 5.1.1 on 2024-10-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0002_contato_empresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="empresa",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
