# Generated by Django 5.1.1 on 2024-10-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0003_alter_contato_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-01-01 00:00:00"
            ),
            preserve_default=False,
        ),
    ]
