# Generated by Django 5.1.1 on 2024-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gethos_home', '0004_contato_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='email',
        ),
        migrations.AddField(
            model_name='contato',
            name='dataAcao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='dataConsulta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='horaConsulta',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='nomeAnimal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='nomeVet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='tipoAtendimento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=13),
        ),
    ]
