# Generated by Django 5.1.1 on 2025-01-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0005_remove_contato_email_contato_dataacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contato",
            name="dataAcao",
        ),
        migrations.RemoveField(
            model_name="contato",
            name="empresa",
        ),
        migrations.AddField(
            model_name="contato",
            name="obsAtendimento",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contato",
            name="nomeAnimal",
            field=models.CharField(default="teste", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contato",
            name="nomeVet",
            field=models.CharField(default="testeVet", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contato",
            name="status",
            field=models.CharField(
                choices=[
                    ("Agendado", "Agendado"),
                    ("Confirmado", "Confirmado"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Agendado",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contato",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="contato",
            name="tipoAtendimento",
            field=models.CharField(default="tipoAtendimentoTeste", max_length=100),
            preserve_default=False,
        ),
    ]
