# Generated by Django 5.1.1 on 2025-02-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0006_remove_contato_dataacao_remove_contato_empresa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Veterinario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="contato",
            old_name="horaConsulta",
            new_name="hora_consulta",
        ),
        migrations.RenameField(
            model_name="contato",
            old_name="nomeAnimal",
            new_name="nome_animal",
        ),
        migrations.RenameField(
            model_name="contato",
            old_name="obsAtendimento",
            new_name="observacoes",
        ),
        migrations.RenameField(
            model_name="contato",
            old_name="nomeVet",
            new_name="tipo_atendimento",
        ),
        migrations.RemoveField(
            model_name="contato",
            name="dataConsulta",
        ),
        migrations.RemoveField(
            model_name="contato",
            name="tipoAtendimento",
        ),
        migrations.AddField(
            model_name="contato",
            name="data_consulta",
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="contato",
            name="veterinario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gethos_home.veterinario",
            ),
        ),
        migrations.AddIndex(
            model_name="contato",
            index=models.Index(
                fields=["data_consulta"], name="gethos_home_data_co_5b82c1_idx"
            ),
        ),
    ]
