# Generated by Django 5.1.1 on 2025-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0007_veterinario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="empresa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
