# Generated by Django 5.1.1 on 2025-02-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0008_contato_empresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contato",
            name="observacoes",
        ),
    ]
