# Generated by Django 5.1.1 on 2025-02-08 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0009_remove_contato_observacoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensagemWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                ("enviado", models.BooleanField(default=False)),
                ("data_envio", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gethos_home.contato",
                    ),
                ),
            ],
        ),
    ]
