# Generated by Django 5.1.1 on 2025-02-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0011_funnelstage_contactfunnel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactFunnel",
        ),
        migrations.DeleteModel(
            name="FunnelStage",
        ),
    ]
