# Generated by Django 5.1.1 on 2025-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0012_delete_contactfunnel_delete_funnelstage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("mensagem", models.TextField()),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Enviando", "Enviando"),
                            ("Concluída", "Concluída"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "contatos",
                    models.ManyToManyField(
                        related_name="campanhas", to="gethos_home.contato"
                    ),
                ),
            ],
        ),
    ]
