# Generated by Django 5.1.1 on 2025-03-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethos_home", "0013_campanha"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagemwhatsapp",
            name="campanha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gethos_home.campanha",
            ),
        ),
        migrations.AlterField(
            model_name="mensagemwhatsapp",
            name="data_envio",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
